---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "<Cisco UCS Manager Service>"
paths:
  /login:
    get:
      tags:
      - "default"
      description: "Gets a session cookie by logging into \nthe UCS Manager\n"
      operationId: "controllers.default_controller.login_get"
      parameters:
      - name: "host"
        in: "query"
        description: "USC manger host name or IP"
        required: false
        type: "string"
      - name: "user"
        in: "query"
        description: "UCS manger user name"
        required: false
        type: "string"
      - name: "password"
        in: "query"
        description: "UCS manger user password"
        required: false
        type: "string"
      responses:
        200:
          description: "Successful login"
      x-tags:
      - tag: "default"

  /sys:
    get:
      tags:
      - "default"
      description: "Discover USC managed objects"
      operationId: "controllers.default_controller.systemGetAll"
      parameters:
      - name: "host"
        in: "query"
        description: "USC manger host name or IP"
        required: false
        type: "string"
      - name: "user"
        in: "query"
        description: "UCS manger user name"
        required: false
        type: "string"
      - name: "password"
        in: "query"
        description: "UCS manger user password"
        required: false
        type: "string"
      responses:
        200:
          description: "Successful data fetch"
      x-tags:
      - tag: "default"

  /rackmount:
    get:
      tags:
      - "default"
      description: "Discover USC managed rackmount servers"
      operationId: "controllers.default_controller.getRackmount"
      parameters:
      - name: "host"
        in: "query"
        description: "USC manger host name or IP"
        required: false
        type: "string"
      - name: "user"
        in: "query"
        description: "UCS manger user name"
        required: false
        type: "string"
      - name: "password"
        in: "query"
        description: "UCS manger user password"
        required: false
        type: "string"
      responses:
        200:
          description: "Successful data fetch of rackmount"
      x-tags:
      - tag: "default"

  /Catalog/:
    get:
      tags:
      - "default"
      description: "Returns a catalog of rackmount servers"
      operationId: "controllers.default_controller.getCatalog"
      parameters:
      - name: "host"
        in: "query"
        description: "USC manger host name or IP"
        required: false
        type: "string"
      - name: "user"
        in: "query"
        description: "UCS manger user name"
        required: false
        type: "string"
      - name: "password"
        in: "query"
        description: "UCS manger user password"
        required: false
        type: "string"
      - name: "identifier"
        in: "query"
        description: "UCS element dn"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful data fetch of rackmount catalogs"
      x-tags:
      - tag: "default"

definitions: {}
